ENV['RAILS_ENV'] ||= 'test'

require 'rails/all'

require 'rubygems'

require 'active_support'
require 'active_support/core_ext'

require 'RMagick'

require 'kaleidoscope'

require 'active_record'

require 'pry'

require 'paperclip'

ActiveRecord::Base.establish_connection adapter: "sqlite3", database: ":memory:"

load File.dirname(__FILE__) + '/support/schema.rb'
require File.dirname(__FILE__) + '/support/models.rb'

include RSpec::Matchers

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.after(:each) do
    Kaleidoscope.configure do |config|
      config.colors = nil
    end
  end
end